interface SeedProduct {
    description: string;
    images: string[];
    inStock: number;
    price: number;
    sizes: ValidSizes[];
    slug: string;
    tags: string[];
    title: string;
    type: ValidTypes;
    gender: 'men' | 'women' | 'kids'
}

type ValidSizes = 'XS' | 'S' | 'M' | 'L' | 'XL' | 'XXL' | 'XXXL';
type ValidTypes = 'shirts' | 'pants' | 'dress' | 'coats' | 'blazer' | 'knit' | 'jeans' | 'skirts' | 'jackets' | 'suits' | 'overshirts' | 'hoodies' | 't-shirts'

interface SeedData {
    categories: { name: string }[],
    products: SeedProduct[],
}

export const initialData: SeedData = {
    categories: [
        { name: 'Shirts' }, { name: 'Pants' }, { name: 'Dress' }, { name: 'Coats' }, { name: 'Blazer' }, { name: 'Knit' }, { name: 'Jeans' }, { name: 'Skirts' }, { name: 'Jackets' }, { name: 'Suits' }, { name: 'Overshirts' }, { name: 'Hoodies' }, { name: 'T-Shirts' }
    ],
    products: [
        {
            description: "Padded anorak with high collar and hoodie. Long sleeves with elastic cuffs. Welt pockets at front. Interior lining. Front zipper closure and snap buttons hidden by a flap.",
            images: [
                '01.jpg',
                '02.jpg',
                '03.jpg',
                '04.jpg',
                '05.jpg',
            ],
            inStock: 7,
            price: 75,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
            slug: "hooded_puffer_anorak",
            type: 'coats',
            tags: ['anorak'],
            title: "Hooded Puffer Anorak",
            gender: 'women'
        },
        {
            description: "Coat with scarf collar and long sleeves. Hidden side seam pockets. Front double-breasted closure with hidden snap button.",
            images: [
                '06.jpg',
                '07.jpg',
                '08.jpg',
                '09.jpg',
                '10.jpg',
            ],
            inStock: 5,
            price: 200,
            sizes: ['XS', 'S', 'M', 'XL', 'XXL'],
            slug: "short_knit_coat_with_scarf",
            type: 'coats',
            tags: ['coat', 'knit'],
            title: "Short knit coat with scarf",
            gender: 'women'
        },

        {
            description: "Coat with lapel collar and long sleeves with buttons. Front welt pockets. Front double-breasted button closure.",
            images: [
                '11.jpg',
                '12.jpg',
                '13.jpg',
                '14.jpg',
                '15.jpg',
            ],
            inStock: 10,
            price: 130,
            sizes: ['S', 'M', 'L', 'XL', 'XXL'],
            slug: "short_double_breasted_coat",
            type: 'coats',
            tags: ['coat'],
            title: "Short Double-Breasted Coat",
            gender: 'women'
        },

        {
            description: "Midi dress with lapel collar and sleeveless design. Front pocket with flap detail. Pleats at hem. Front button closure.",
            images: [
                '16.jpg',
                '17.jpg',
                '18.jpg',
                '19.jpg',
                '20.jpg',
            ],
            inStock: 50,
            price: 45,
            sizes: ['XS', 'S', 'M', 'L'],
            slug: "midi_shirt_dress",
            type: 'dress',
            tags: ['shirt', 'dress'],
            title: "Midi Shirtdress",
            gender: 'women'
        },
        {
            description: "Midi dress with mock neck and sleeveless design. Adjustable self belt with metal buckle. Hidden in-seam zip closure.",
            images: [
                '21.jpg',
                '22.jpg',
                '23.jpg',
                '24.jpg',
                '25.jpg',
            ],
            inStock: 50,
            price: 40,
            sizes: ['M', 'L', 'XL', 'XXL'],
            slug: "twill_belted_dress",
            type: 'dress',
            tags: ['dress'],
            title: "Twill belted dress",
            gender: 'women'
        },
        {
            description: "Midi shirt dress with a lapel collar and short sleeves with buttoned cuffs. Adjustable waist with a tie in the same fabric. Godet detail. Front closure with hidden buttons.",
            images: [
                '26.jpg',
                '27.jpg',
                '28.jpg',
                '29.jpg',
                '30.jpg',
            ],
            inStock: 5,
            price: 35,
            sizes: ['M', 'L', 'XL', 'XXL'],
            slug: "plaid_godet_shirt_dress",
            type: 'dress',
            tags: ['dress'],
            title: "Plaid godet shirt dress",
            gender: 'women'
        },
        {
            description: "Plaid godet shirt dress.",
            images: [
                '31.jpg',
                '32.jpg',
                '33.jpg',
                '34.jpg',
                '35.jpg',
            ],
            inStock: 15,
            price: 35,
            sizes: ['S', 'M', 'L', 'XL'],
            slug: "pleated_midi_dress",
            type: 'dress',
            tags: ['dress'],
            title: "Pleated midi dress",
            gender: 'women'
        },
        {
            description: "Long sleeve blazer with lapel collar. Welt pockets with flap. Front button closure.",
            images: [
                '36.jpg',
                '37.jpg',
                '38.jpg',
                '39.jpg',
                '40.jpg'
            ],
            inStock: 17,
            price: 35,
            sizes: ['XS', 'S', 'XL', 'XXL'],
            slug: "basic_linen_blazer",
            type: 'blazer',
            tags: ['blazer'],
            title: "Basic linen blazer",
            gender: 'women'
        },
        {
            description: "Mid-rise pants with hidden side seam pockets. Front pleat detail. Front zip and button closure.",
            images: [
                '41.jpg',
                '42.jpg',
                '43.jpg',
                '44.jpg',
                '45.jpg',
            ],
            inStock: 12,
            price: 35,
            sizes: ['XS', 'S', 'M'],
            slug: "pleated_pants",
            type: 'pants',
            tags: ['pants'],
            title: "Pleated pants",
            gender: 'women'
        },
        {
            description: "Shorts made from a cotton and polyamide blend. Low-rise with elastic waistband. Hem detail finished with tonal lace application adjustable with buttons.",
            images: [
                '46.jpg',
                '47.jpg',
                '48.jpg',
                '49.jpg',
                '50.jpg',
            ],
            inStock: 5,
            price: 35,
            sizes: ['XS', 'S'],
            slug: "fine_knit_lace_pants",
            type: 'pants',
            tags: ['pants'],
            title: "Fine knit lace pants",
            gender: 'women'
        },
        {
            description: "Full cut jumper made of wool. V-neck and long sleeves.",
            images: [
                '51.jpg',
                '52.jpg',
                '53.jpg',
                '54.jpg',
                '55.jpg',
            ],
            inStock: 2,
            price: 35,
            sizes: ['XS', 'S', 'M'],
            slug: "oversized_wool_jumper",
            type: 'knit',
            tags: ['knit'],
            title: "Oversized wool jumper",
            gender: 'women'
        },
        {
            description: "Knit jumper with round neck and long sleeves. Asymmetrical hem with scarf-style fabric finished with fringes in the same fabric.",
            images: [
                '56.jpg',
                '57.jpg',
                '58.jpg',
                '59.jpg',
                '60.jpg',
            ],
            inStock: 82,
            price: 35,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
            slug: "fringe_scarf_knit_jumper",
            type: 'knit',
            tags: ['knit'],
            title: "Fringe scarf knit jumper",
            gender: 'women'
        },
        {
            description: "Midi skirt made of knit fabric. Mid-rise with elastic waistband.",
            images: [
                '61.jpg',
                '62.jpg',
                '63.jpg',
                '64.jpg',
                '65.jpg',
            ],
            inStock: 24,
            price: 35,
            sizes: ['XL', 'XXL'],
            slug: "asymmetric_knit_midi_skirt",
            type: 'knit',
            tags: ['knit'],
            title: "Asymmetric knit midi skirt",
            gender: 'women'
        },
        {
            description: "High neck midi dress with sleeveless design. Draped fabric detail. Back hidden in-seam zip closure.",
            images: [
                '66.jpg',
                '67.jpg',
                '68.jpg',
                '69.jpg',
                '70.jpg',
            ],
            inStock: 5,
            price: 30,
            sizes: ['XS', 'S', 'XXL'],
            slug: "draped_high_neck_dress",
            type: 'dress',
            tags: ['dress'],
            title: "Draped high neck dress",
            gender: 'women'
        },
        {
            description: "Halter bodysuit made of ribbed fabric. Open back.",
            images: [
                '71.jpg',
                '72.jpg',
                '73.jpg',
                '74.jpg',
                '75.jpg',
            ],
            inStock: 150,
            price: 30,
            sizes: ['M', 'L'],
            slug: "seamless_halter_bodysuit",
            type: 'shirts',
            tags: ['shirt'],
            title: "Seamless halter bodysuit",
            gender: 'women'
        },
        {
            description: "Low-rise jeans with five pockets. Straight leg. Front pronounced seam detail. Front zip and button closure.",
            images: [
                '76.jpg',
                '77.jpg',
                '78.jpg',
                '79.jpg',
                '80.jpg',
            ],
            inStock: 10,
            price: 35,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
            slug: "low_rise_straight_seam_detail",
            type: 'jeans',
            tags: ['jeans'],
            title: "Low Rise - Straight - Seam detail",
            gender: 'women'
        },
        {
            description: "Mid-rise jeans with belt loops. Five pockets. Pressed crease on the front. Washed effect. Frayed hem with a flared design. Front zip and button closure.",
            images: [
                '81.jpg',
                '82.jpg',
                '83.jpg',
                '84.jpg',
                '85.jpg',
            ],
            inStock: 34,
            price: 35,
            sizes: ['XS', 'S', 'M', 'L'],
            slug: "mid_rise_cropped_flare_jeans",
            type: 'jeans',
            tags: ['jeans'],
            title: "Mid rise cropped flare jeans",
            gender: 'women'
        },
        {
            description: "High-waisted jeans with belt loops. Five pockets. Pressed crease detail on the front. Front zip and button closure.",
            images: [
                '86.jpg',
                '87.jpg',
                '88.jpg',
                '89.jpg',
                '90.jpg',
            ],
            inStock: 15,
            price: 40,
            sizes: ['XL', 'XXL'],
            slug: "high_waist_tapered_leg_ankle_length",
            type: 'shirts',
            tags: ['shirt'],
            title: "High waist - Tapered leg - Ankle length",
            gender: 'women'
        },
        {
            description: "Low-rise jeans with belt loops and five pockets. Flare hem. Front zip and metal button closure.",
            images: [
                '91.jpg',
                '92.jpg',
                '93.jpg',
                '94.jpg',
                '95.jpg',
            ],
            inStock: 12,
            price: 40,
            sizes: ['XS', 'XXL'],
            slug: "bootcut_low_rise_jeans",
            type: 'jeans',
            tags: ['jeans'],
            title: "Bootcut low rise jeans",
            gender: 'women'
        },
        {
            description: "High-waisted, ankle-length jeans with five pockets. Slim, short flared leg. Front zip and button closure.",
            images: [
                '96.jpg',
                '97.jpg',
                '98.jpg',
                '99.jpg',
                '100.jpg',
            ],
            inStock: 10,
            price: 115,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
            slug: "mini_flare_high_rise_jeans",
            type: 'jeans',
            tags: ['jeans'],
            title: "Mini flare high rise jeans",
            gender: 'women'
        },
        {
            description: "Mid-rise jeans with belt loops and five pockets. Twisted seam detail. Front zip and metal button closure.",
            images: [
                '101.jpg',
                '102.jpg',
                '103.jpg',
                '104.jpg',
                '105.jpg',
            ],
            inStock: 10,
            price: 130,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
            slug: "mid_rise_cropped_jeans",
            type: 'jeans',
            tags: ['jeans'],
            title: "Mid rise cropped jeans",
            gender: 'women'
        },
        {
            description: "High-rise jeans with front pockets. Flared hem. Zip, button and metal hook closure.",
            images: [
                '106.jpg',
                '107.jpg',
                '108.jpg',
                '109.jpg',
                '110.jpg',
            ],
            inStock: 100,
            price: 85,
            sizes: ['XS', 'L', 'XL', 'XXL'],
            slug: "mid_rise_flare_jeans",
            type: 'jeans',
            tags: ['jeans'],
            title: "Mid rise flare jeans",
            gender: 'women'
        },
        {
            description: "Mid-rise skirt with belt loops. Washed effect. Godet detail and defined seams. Asymmetrical raw-cut hem. Front zip and metal button closure.",
            images: [
                '116.jpg',
                '117.jpg',
                '118.jpg',
                '119.jpg',
                '120.jpg',
            ],
            inStock: 7,
            price: 85,
            sizes: ['XS', 'S', 'M'],
            slug: "denim_godet_skirt",
            type: 'skirts',
            tags: ['skirts'],
            title: "Denim godet skirt",
            gender: 'women'
        },
        {
            description: "Mid-rise short skirt. Faux welt pockets at front. Waist with belt loops.",
            images: [
                '121.jpg',
                '122.jpg',
                '123.jpg',
                '124.jpg',
                '125.jpg',
            ],
            inStock: 15,
            price: 85,
            sizes: ['XS', 'S', 'M', 'L'],
            slug: "knit_pocket_mini_skirt",
            type: 'skirts',
            tags: ['skirt'],
            title: "Knit pocket mini skirt",
            gender: 'women'
        },
        {
            description: "Mid-rise midi skirt. Asymmetric hem. Side metal zip closure.",
            images: [
                '126.jpg',
                '127.jpg',
                '128.jpg',
                '129.jpg',
                '130.jpg',
            ],
            inStock: 15,
            price: 70,
            sizes: ['XS', 'S', 'XL', 'XXL'],
            slug: "denim_midi_skirt",
            type: 'skirts',
            tags: ['skirt'],
            title: "Denim midi skirt",
            gender: 'women'
        },
        {
            description: "High-waisted midi skirt with elastic waistband. Pleat detail. Puffball hem with interior elastic.",
            images: [
                '131.jpg',
                '132.jpg',
                '133.jpg',
                '134.jpg',
                '135.jpg',
            ],
            inStock: 13,
            price: 60,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
            slug: "puffball_midi_skirt",
            type: 'skirts',
            tags: ['skirt'],
            title: "Puffball midi skirt",
            gender: 'women'
        },
        {
            description: "Mid-rise midi skirt. Front pockets. Asymmetric hem. Side hidden in-seam zip closure.",
            images: [
                '136.jpg',
                '137.jpg',
                '138.jpg',
                '139.jpg',
                '140.jpg',
            ],
            inStock: 11,
            price: 30,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
            slug: "asymmetric_midi_skirt",
            type: 'skirts',
            tags: ['skirt'],
            title: "Asymmetric midi skirt",
            gender: 'women'
        },
        {
            description: "Mid-rise midi skirt. Adjustable waist with tie. Hidden side seam pockets.",
            images: [
                '141.jpg',
                '142.jpg',
                '143.jpg',
                '144.jpg',
            ],
            inStock: 13,
            price: 35,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
            slug: "polka_dot_midi_skirt",
            type: 'skirts',
            tags: ['skirt'],
            title: "Polka dot midi skirt",
            gender: 'women'
        },
        {
            description: "Flowy V-neck blouse with self ties. Long sleeves with cuffs. Asymmetric rounded hem.",
            images: [
                '146.jpg',
                '147.jpg',
                '148.jpg',
                '149.jpg',
                '150.jpg',
            ],
            inStock: 85,
            price: 225,
            sizes: ['XS', 'S', 'M'],
            slug: "tied_neckline_blouse",
            type: 'shirts',
            tags: ['shirts'],
            title: "Tied neckline blouse",
            gender: 'women'
        },
        {
            description: "Top with contrast lapel collar, tie detail, and long sleeves with elastic cuffs. Flap pockets on the front. Elastic hem. Front button closure.",
            images: [
                '151.jpg',
                '152.jpg',
                '153.jpg',
                '154.jpg',
                '155.jpg',
            ],
            inStock: 10,
            price: 130,
            sizes: ['XS', 'S', 'M', 'XXL'],
            slug: "contrast_collar_poplin_top",
            type: 'shirts',
            tags: ['shirt'],
            title: "Contrast collar poplin top",
            gender: 'women'
        },
        {
            description: "Blouse with V-neckline, ruffles, and long sleeves with elastic cuffs. Faux front buttons.",
            images: [
                '156.jpg',
                '157.jpg',
                '158.jpg',
                '159.jpg',
                '160.jpg',
            ],
            inStock: 9,
            price: 110,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
            slug: "ruffled_blouse",
            type: 'shirts',
            tags: ['shirts'],
            title: "Ruffled blouse",
            gender: 'women'
        },
        {
            description: "Relaxed fit jacket made of cotton denim. Lapel collar and long sleeves with buttoned cuffs. Front patch pockets. Front button closure.",
            images: [
                '161.jpg',
                '162.jpg',
                '163.jpg',
                '164.jpg',
                '165.jpg',
            ],
            inStock: 10,
            price: 45,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
            slug: "relaxed_fit_denim_jacket_with_pockets",
            type: 'jackets',
            tags: ['jackets'],
            title: "Relaxed fit denim jacket with pockets",
            gender: 'men'
        },
        {
            description: "Cropped fit jacket made from a wool blend fabric. Lapel collar and long sleeves with buttoned cuffs. Contrasting inner lining. Welt pockets at hip. Interior pocket detail. Front zip closure.",
            images: [
                '166.jpg',
                '167.jpg',
                '168.jpg',
                '169.jpg',
            ],
            inStock: 0,
            price: 40,
            sizes: ['XS', 'S'],
            slug: "wool_blend_jacket",
            type: 'jackets',
            tags: ['jackets'],
            title: "Wool blend jacket",
            gender: 'men'
        },
        {
            description: "Relaxed fit parka made of cotton fabric with a washed finish. High collar and long sleeves. Welt pockets at chest and patch pockets at hip. Front zip closure hidden by a snap button placket.",
            images: [
                '171.jpg',
                '172.jpg',
                '173.jpg',
                '174.jpg',
                '175.jpg',
            ],
            inStock: 30,
            price: 35,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
            slug: "washed_relaxed_fit_denim_parka",
            type: 'jackets',
            tags: ['jackets'],
            title: "Washed relaxed fit denim parka",
            gender: 'men'
        },
        {
            description: "Regular fit pants made of wool fabric. Front pockets and back welt pockets with button. Front zip and button closure.",
            images: [
                '176.jpg',
                '177.jpg',
                '178.jpg',
                '179.jpg',
                '180.jpg',
            ],
            inStock: 16,
            price: 40,
            sizes: ['XS', 'S', 'L', 'XL', 'XXL'],
            slug: "wool_suit_pants",
            type: 'pants',
            tags: ['pants'],
            title: "Wool suit pants",
            gender: 'men'
        },
        {
            description: "Regular fit pants made of technical fabric with cotton blend. Elastic waistband. Side pockets and welt back pockets. Front zip and button closure.",
            images: [
                '181.jpg',
                '182.jpg',
                '183.jpg',
                '184.jpg',
                '185.jpg',

            ],
            inStock: 18,
            price: 35,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
            slug: "technical_jogger_waist_pants",
            type: 'pants',
            tags: ['pants'],
            title: "Technical jogger waist pants",
            gender: 'men'
        },
        {
            description: "Regular fit knit polo shirt made of cotton-blend yarn. Lapel collar with front opening. Long sleeves. Ribbed trim.",
            images: [
                '186.jpg',
                '187.jpg',
                '188.jpg',
                '189.jpg',
                '190.jpg',
            ],
            inStock: 5,
            price: 35,
            sizes: ['XL', 'XXL'],
            slug: "textured_knit_polo_shirt",
            type: 'knit',
            tags: ['knit'],
            title: "Textured knit polo shirt",
            gender: 'men'
        },
        {
            description: "Relaxed fit cotton knit cardigan. V-neck and long sleeves. Ribbed trim with distressed effect. Front button closure.",
            images: [
                '191.jpg',
                '192.jpg',
                '193.jpg',
                '194.jpg',
                '195.jpg',
            ],
            inStock: 16,
            price: 35,
            sizes: ['S', 'M'],
            slug: "distressed_ribbed_cardigan",
            type: 'knit',
            tags: ['knit'],
            title: "Distressed ribbed cardigan",
            gender: 'men'
        },
        {
            description: "Regular fit cardigan knitted with a wool and 5% cashmere blend yarn. V-neck and long sleeves. Ribbed trim. Front button closure.",
            images: [
                '196.jpg',
                '197.jpg',
                '198.jpg',
                '199.jpg',
                '200.jpg',
            ],
            inStock: 10,
            price: 130,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
            slug: "regular_fit_blend_wool_cardigan",
            type: 'knit',
            tags: ['knit'],
            title: "Regular fit blend wool cardigan",
            gender: 'men'
        },
        {
            description: "Notched lapel collar and long sleeves with buttoned cuffs. Welt pocket at chest. Flap pockets at hip. Interior pocket detail. Hem with back vents. Front button closure.",
            images: [
                '201.jpg',
                '202.jpg',
                '203.jpg',
                '204.jpg',
            ],
            inStock: 3,
            price: 90,
            sizes: ['M', 'L', 'XL', 'XXL'],
            slug: "wool_suit_blazer_",
            type: 'suits',
            tags: ['suits'],
            title: "Wool suit blazer",
            gender: 'men'
        },
        {
            description: "Regular fit blazer made of linen fabric. Half lining on the inside. Notched lapel collar and long sleeves finished in buttoned cuffs. Welt pocket at chest and flap pockets at hip. Interior pocket detail. Hem with vents at the back. Front button fastening.",
            images: [
                '206.jpg',
                '207.jpg',
                '208.jpg',
                '209.jpg',
                '210.jpg',
            ],
            inStock: 162,
            price: 100,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
            slug: "linen_suit_blazer",
            type: 'suits',
            tags: ['suits'],
            title: "Linen suit blazer",
            gender: 'men'
        },
        {
            description: "Notch lapel collar and long sleeves with buttoned cuffs. Welt pocket at chest. Flap pockets at hip. Interior pocket detail. Back vent. Front button closure.",
            images: [
                '211.jpg',
                '212.jpg',
                '213.jpg',
                '214.jpg',
            ],
            inStock: 10,
            price: 30,
            sizes: ['XS', 'S', 'M'],
            slug: "wool_suit_jacket",
            type: 'suits',
            tags: ['suits'],
            title: "Wool suit jacket",
            gender: 'men'
        },
        {
            description: "Regular fit blazer made of a wool and cotton blend fabric. Notched lapel collar. Long sleeves with buttoned cuffs. Welt pockets at chest and patch pockets at hip. Interior pocket detail. Hem with vent at center back. Front button closure.",
            images: [
                '216.jpg',
                '217.jpg',
                '218.jpg',
                '219.jpg',
                '220.jpg',
            ],
            inStock: 0,
            price: 25,
            sizes: ['XS', 'S', 'M'],
            slug: "wool_cottom_textured_blazer",
            type: 'blazer',
            tags: ['blazer'],
            title: "Wool cottom textured blazer",
            gender: 'men'
        },
        {
            description: "Regular fit blazer made of wool blend fabric. Notched lapel collar and long sleeves with buttoned cuffs. Welt pocket at chest and flap pockets at hip. Interior pocket detail. Hem with vents at back. Front button closure.",
            images: [
                '221.jpg',
                '222.jpg',
                '223.jpg',
                '224.jpg',
                '225.jpg',
            ],
            inStock: 10,
            price: 25,
            sizes: ['XS', 'S', 'M'],
            slug: "wool_suit_blazer",
            type: 'blazer',
            tags: ['blazer'],
            title: "Wool suit blazer",
            gender: 'men'
        },
        {
            description: "Regular fit overshirt made of linen and cotton fabric. Lapel collar and long sleeves with buttoned cuffs. Chest patch pocket. Side pockets at hip. Washed effect. Front button closure.",
            images: [
                '226.jpg',
                '227.jpg',
                '228.jpg',
                '229.jpg',
                '230.jpg',
            ],
            inStock: 10,
            price: 30,
            sizes: ['XS', 'S', 'M'],
            slug: "linen_cottom_pocket_overshirt",
            type: 'overshirts',
            tags: ['overshirts'],
            title: "Linen cottom pocket overshirt",
            gender: 'men'
        },
        {
            description: "Cropped fit overshirt made of lightweight cotton fabric. Lapel collar and long sleeves with buttoned cuffs. Elasticated hem at back. Front button closure.",
            images: [
                '231.jpg',
                '232.jpg',
                '233.jpg',
                '234.jpg',
                '235.jpg',
            ],
            inStock: 10,
            price: 30,
            sizes: ['XS', 'S', 'M'],
            slug: "plaid_overshirt",
            type: 'overshirts',
            tags: ['overshirts'],
            title: "Plaid overshirt",
            gender: 'men'
        },
        {
            description: "Relaxed fit shirt made of linen and cotton blend fabric. Buttoned collar and long sleeves with buttoned cuffs. Chest patch pocket. Front button closure.",
            images: [
                '236.jpg',
                '237.jpg',
                '238.jpg',
                '239.jpg',
                '240.jpg',
            ],
            inStock: 10,
            price: 30,
            sizes: ['XS', 'S', 'M'],
            slug: "linen_cotton_shirt",
            type: 'shirts',
            tags: ['shirts'],
            title: "Linen cotton shirt",
            gender: 'men'
        },
        {
            description: "Relaxed fit shirt made of linen fabric. Italian collar and long sleeves with buttoned cuffs. Slightly washed effect. Front button closure.",
            images: [
                '241.jpg',
                '242.jpg',
                '243.jpg',
                '244.jpg',
                '245.jpg',
            ],
            inStock: 16,
            price: 25,
            sizes: ['XS', 'S'],
            slug: "washed_linen_shirt",
            type: 'shirts',
            tags: ['shirt'],
            title: "Washed linen shirt",
            gender: 'men'
        },
        {
            description: "Regular fit shirt made of cotton blend fabric. Lapel collar and long sleeves with buttoned cuffs. Chest patch pocket. Front button closure.",
            images: [
                '246.jpg',
                '247.jpg',
                '248.jpg',
                '249.jpg',
                '250.jpg',
            ],
            inStock: 0,
            price: 30,
            sizes: ['XS', 'S'],
            slug: "regular_fit_textured_shirt",
            type: 'shirts',
            tags: ['shirts'],
            title: "Regular fit textured shirt",
            gender: 'men'
        },
        {
            description: "Relaxed fit shirt made of wool and viscose fabric. Lapel collar and long sleeves with buttoned cuffs. Front button closure.",
            images: [
                '251.jpg',
                '252.jpg',
                '253.jpg',
                '254.jpg',
                '255.jpg',
            ],
            inStock: 10,
            price: 30,
            sizes: ['XS', 'S'],
            slug: "flowy_wool_shirt",
            type: 'shirts',
            tags: ['shirts'],
            title: "Flowy wool shirt",
            gender: 'men'
        },
        {
            description: "Relaxed fit shirt made from a cotton blend fabric. Lapel collar and long sleeves with buttoned cuffs. Front button closure.",
            images: [
                '256.jpg',
                '257.jpg',
                '258.jpg',
                '259.jpg',
                '260.jpg',
            ],
            inStock: 10,
            price: 65,
            sizes: ['XS', 'S', 'M'],
            slug: "striped_jacquard_shirt",
            type: 'shirts',
            tags: ['shirts'],
            title: "Striped jacquard shirt",
            gender: 'men'
        },
        {
            description: "Relaxed fit shirt made of lyocell and linen fabric. Spread collar and long sleeves with buttoned cuffs. Chest patch pocket. Front button closure.",
            images: [
                '261.jpg',
                '262.jpg',
                '263.jpg',
                '264.jpg',
                '265.jpg',
            ],
            inStock: 10,
            price: 30,
            sizes: ['XS', 'S', 'M'],
            slug: "flowy_lyocell_linen_shirt",
            type: 'shirts',
            tags: ['shirt'],
            title: "Flowy lyocell linen shirt",
            gender: 'men'
        },
        {
            description: "Long rubberized coat with hoodie and long sleeves with elastic cuffs. Front heat-sealed zip closure and hidden side seam pockets. Elasticized hem.",
            images: [
                '300.jpg',
                '301.jpg',
                '302.jpg',
            ],
            inStock: 14,
            price: 18,
            sizes: ['XS', 'S', 'M'],
            slug: "long_rubberized_puffer_coat",
            type: 'coats',
            tags: ['coats'],
            title: "Long rubberized puffer coat",
            gender: 'kids'
        },
        {
            description: "Long sleeve hoodie with ribbed trim.",
            images: [
                '303.jpg',
                '304.jpg',
                '305.jpg',
            ],
            inStock: 10,
            price: 9,
            sizes: ['XS', 'S', 'M'],
            slug: "kpop_hoodie",
            type: 'hoodies',
            tags: ['hoodies'],
            title: "Kpop hoodie",
            gender: 'kids'
        },
        {
            description: "Ribbed dress with round neck and short sleeves. Ribbed trim with contrasting color. Flared skirt. Text print on the front.",
            images: [
                '306.jpg',
                '307.jpg',
                '308.jpg',
            ],
            inStock: 10,
            price: 5,
            sizes: ['XS', 'S', 'M'],
            slug: "text_print_ribbed_dress",
            type: 'dress',
            tags: ['dress'],
            title: "Text print ribbed dress",
            gender: 'kids'
        },
        {
            description: "Long balloon-style overalls with a straight neckline and straps with a front buckle closure. Patch pocket on the bib. Front pockets and patch pockets on the back. Striped print.",
            images: [
                '309.jpg',
                '310.jpg',
            ],
            inStock: 10,
            price: 5,
            sizes: ['XS', 'S', 'M'],
            slug: "striped_balloon_denim_overalls",
            type: 'jeans',
            tags: ['jeans'],
            title: "Striped balloon denim overalls",
            gender: 'kids'
        },
        {
            description: "Bomber jacket with a high collar and long sleeves. Ribbed trim. Front welt pockets.",
            images: [
                '311.jpg',
                '312.jpg',
            ],
            inStock: 1,
            price: 12,
            sizes: ['XS', 'S', 'M'],
            slug: "bomber_jacket",
            type: 'jackets',
            tags: ['jacket'],
            title: "Bomber jacket",
            gender: 'kids'
        },
        {
            description: "Hoodie sweatshirt with long sleeves. Ribbed trim. Front kangaroo pocket with label appliqué.",
            images: [
                '313.jpg',
                '314.jpg',
                '315.jpg',
            ],
            inStock: 4,
            price: 9,
            sizes: ['XS', 'S', 'M'],
            slug: "hoodie_sweatshirt",
            type: 'hoodies',
            tags: ['hoodies'],
            title: "Hoodie sweatshirt",
            gender: 'kids'
        },
        {
            description: "Round neck short sleeve T-shirt.",
            images: [
                '316.jpg',
                '317.jpg',
                '318.jpg',
            ],
            inStock: 40,
            price: 4,
            sizes: ['XS', 'S', 'M'],
            slug: "tee_shirt",
            type: 't-shirts',
            tags: ['t-shirt'],
            title: "Tee shirt",
            gender: 'kids'
        }
    ]
}